///////////////////////////////////////////////////////////////////////////////
// DataProviderInterfaces.h

#pragma once

#include "TcInterfaces.h"
#include "TcIoInterfaces.h"
#include "TcRtInterfaces.h"
#include "DataProviderServices.h"

///<AutoGeneratedContent id="Interfaces">
///</AutoGeneratedContent>
