///////////////////////////////////////////////////////////////////////////////
// DataProviderClassFactory.cpp
#include "TcPch.h"
#pragma hdrstop

#include "DataProviderClassFactory.h"
#include "DataProviderServices.h"
#include "DataProviderVersion.h"
#include "Module1.h"

BEGIN_CLASS_MAP(CDataProviderClassFactory)
///<AutoGeneratedContent id="ClassMap">
	CLASS_ENTRY_LIB(VID_DataProvider, CID_DataProviderCModule1, SRVNAME_DATAPROVIDER "!CModule1", CModule1)
///</AutoGeneratedContent>
END_CLASS_MAP()

CDataProviderClassFactory::CDataProviderClassFactory() : CObjClassFactory()
{
	TcDbgUnitSetImageName(TCDBG_UNIT_IMAGE_NAME_TMX(SRVNAME_DATAPROVIDER));
#if defined(TCDBG_UNIT_VERSION)
	TcDbgUnitSetVersion(TCDBG_UNIT_VERSION(DataProvider));
#endif //defined(TCDBG_UNIT_VERSION)
}

