///////////////////////////////////////////////////////////////////////////////
// DataProviderServices.h

#pragma once

#include "TcServices.h"

const ULONG DrvID_DataProvider = 0x3F000000;
#define SRVNAME_DATAPROVIDER "DataProvider"

///<AutoGeneratedContent id="ClassIDs">
const CTCID CID_DataProviderCModule1 = {0x4b18191a,0x07b7,0x4e01,{0xb6,0xaf,0xa4,0x89,0x54,0x76,0x72,0x64}};
///</AutoGeneratedContent>

///<AutoGeneratedContent id="ParameterIDs">
///</AutoGeneratedContent>

///<AutoGeneratedContent id="DataTypes">
typedef struct _Module1DataArea1
{
	ULONG Value;
} Module1DataArea1, *PModule1DataArea1;

///</AutoGeneratedContent>



///<AutoGeneratedContent id="DataAreaIDs">
#define ADI_Module1DataArea1 1
///</AutoGeneratedContent>

///<AutoGeneratedContent id="InterfaceIDs">
///</AutoGeneratedContent>

///<AutoGeneratedContent id="EventClasses">
///</AutoGeneratedContent>
