///////////////////////////////////////////////////////////////////////////////
// Untitled1Services.h

#pragma once

#include "TcServices.h"

const ULONG DrvID_Untitled1 = 0x3F000000;
#define SRVNAME_UNTITLED1 "Untitled1"

///<AutoGeneratedContent id="ClassIDs">
const CTCID CID_Untitled1CModule1 = {0x906abe87,0x9de8,0x44bd,{0xb4,0x8e,0x28,0x64,0x8c,0x60,0x6b,0x4f}};
///</AutoGeneratedContent>

///<AutoGeneratedContent id="ParameterIDs">
const PTCID PID_Module1Parameter = 0x00000001;
const PTCID PID_Module1DataPointer1 = 0x00000002;
///</AutoGeneratedContent>

///<AutoGeneratedContent id="DataTypes">
typedef struct _Module1Parameter
{
	ULONG data1;
	ULONG data2;
	double data3;
} Module1Parameter, *PModule1Parameter;

#pragma pack(push,1)
typedef struct _Module1Inputs
{
	ULONG Value;
	ULONG Status;
	ULONG Data;
	USHORT StatusWord;
} Module1Inputs, *PModule1Inputs;
#pragma pack(pop)

#pragma pack(push,1)
typedef struct _Module1Outputs
{
	ULONG Value;
	ULONG Control;
	ULONG Data;
	USHORT ControlWord;
} Module1Outputs, *PModule1Outputs;
#pragma pack(pop)

///</AutoGeneratedContent>



///<AutoGeneratedContent id="DataAreaIDs">
#define ADI_Module1Inputs 0
#define ADI_Module1Outputs 1
///</AutoGeneratedContent>

///<AutoGeneratedContent id="InterfaceIDs">
///</AutoGeneratedContent>

///<AutoGeneratedContent id="EventClasses">
///</AutoGeneratedContent>
